### ISSUE TITLE
Microsoft SSAS compatibility?

### ISSUE THREAD

**Issue by NaabSunde** [masakoodaa/pythondump#1]
I've reason to believe(and loads of evidence) that Taksibussi.py (later referred as the program) does not support the syntax of SSAS. 
I have to make an analysis on the ratio of "Bussi" and "Taksibussi" and I cannot even comprehend how on Earth could I achieve such a task without Microsoft SQL Server Analysis Services.

Possible fixes for this issue:
- Needs more PHP. Like, who uses Python?
- Add blockchain.

Improvements:
- Code is too inefficient to be ran on a Wolverhampton Instrument for Teaching Computing from Harwell (WITCH).
- Heavy simulations should be made cluster computing compatible and it should support multi-threaded workloads.
- You must take into account the GDPR in the syntax of your code. Leakage of users information might not be impossible at this time.

Edit: Added more improvements

**Comment by masakoodaa** [comment]
www.fizzbuzz.enterprises
